version: '3.5'

services:

  proxy:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - "frontend"
      - "backend"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro

  frontend:
    image: zeenmy/structuresaverweb-frontend
    ports:
      - 3000:3000

  backend:
    image: zeenmy/structuresaverweb-backend
    depends_on:
      - "db"
    ports:
      - 3001:3001
    environment:
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "VerySecretPassword"
      DATABASE_HOST:     "db"

  db:
    image: "postgres"
    environment:
      POSTGRES_USER:     "postgres"
      POSTGRES_PASSWORD: "VerySecretPassword"
      POSTGRES_DB:       "structuresaver"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

  