FROM node:10.17.0-alpine3.9

RUN adduser -D structuresaver
WORKDIR /home/structuresaver

COPY frontend .
RUN chown -R structuresaver .

USER structuresaver
RUN npm install
RUN npm run build
RUN npm install serve

EXPOSE 3000

CMD ["npx", "serve", "-l", "3000", "-s", "build"]
